FROM python:3.13.5-slim

WORKDIR /app

RUN apt-get update && apt-get install -y build-essential

COPY backend/requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]